[build]
  command = "make build"
  functions = "functions"
  publish = "./"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/tommycwu/okta-go-event-hook"
[[redirects]]
  from = "/userTransfer/*"
  to = "/.netlify/functions/hello-lambda/:splat"
  status = 200